USE [master]
GO

/****** Object:  Database [TestDemo]    Script Date: 22-05-2021 18:35:00 ******/
CREATE DATABASE [TestDemo]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TestDemo', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\TestDemo.mdf' , SIZE = 3264KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'TestDemo_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\TestDemo_log.ldf' , SIZE = 816KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [TestDemo] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TestDemo].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TestDemo] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TestDemo] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TestDemo] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TestDemo] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TestDemo] SET ARITHABORT OFF 
GO

ALTER DATABASE [TestDemo] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [TestDemo] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TestDemo] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TestDemo] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TestDemo] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TestDemo] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TestDemo] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TestDemo] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TestDemo] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TestDemo] SET  ENABLE_BROKER 
GO

ALTER DATABASE [TestDemo] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TestDemo] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TestDemo] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TestDemo] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TestDemo] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TestDemo] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TestDemo] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TestDemo] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [TestDemo] SET  MULTI_USER 
GO

ALTER DATABASE [TestDemo] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TestDemo] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TestDemo] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TestDemo] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [TestDemo] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TestDemo] SET  READ_WRITE 
GO


